args = commandArgs(trailingOnly=TRUE)
library(stringr)
library(readr)
library(dplyr)


new_bd = read_tsv(args[1],col_types=cols_only(
EID = col_character(),
Sex.0.0 = col_character(),
`Month of birth.0.0` = col_character(),
`Year of birth.0.0` = col_double(),
`Place of birth in UK - north co-ordinate.0.0` = col_double(),
`Place of birth in UK - north co-ordinate.1.0` = col_double(),
`Place of birth in UK - north co-ordinate.2.0` = col_double(),
`Townsend deprivation index at recruitment.0.0` = col_double(),
`Treatment/medication code.0.0` = col_character(),
`Myopia diagnosis.0.0`=col_character(),
`Age completed full time education.0.0` = col_double(),
`Age at recruitment.0.0` = col_double(),
`Age completed full time education.1.0` = col_double(),
`Age completed full time education.2.0` = col_double(),
`Sleep duration.0.0` = col_double(),
`Sleep duration.1.0` = col_double(),
`Sleep duration.2.0` = col_double(),
`Sleep duration.3.0` = col_double(),
`Getting up in morning.0.0` = col_character(),
`Getting up in morning.1.0` = col_character(),
`Getting up in morning.2.0` = col_character(),
`Getting up in morning.3.0` = col_character(),
`Morning/evening person (chronotype).0.0` = col_character(),
`Morning/evening person (chronotype).1.0` = col_character(),
`Morning/evening person (chronotype).2.0` = col_character(),
`Morning/evening person (chronotype).3.0` = col_character(),
`Nap during day.0.0` = col_character(),
`Nap during day.1.0` = col_character(),
`Nap during day.2.0` = col_character(),
`Nap during day.3.0` = col_character(),
`Sleeplessness / insomnia.0.0` = col_character(),
`Sleeplessness / insomnia.1.0` = col_character(),
`Sleeplessness / insomnia.2.0` = col_character(),
`Sleeplessness / insomnia.3.0` = col_character(),
Snoring.0.0 = col_character(),
Snoring.1.0 = col_character(),
Snoring.2.0 = col_character(),
Snoring.3.0 = col_character(),
`Daytime dozing / sleeping (narcolepsy).0.0` = col_character(),
`Daytime dozing / sleeping (narcolepsy).1.0` = col_character(),
`Daytime dozing / sleeping (narcolepsy).2.0` = col_character(),
`Daytime dozing / sleeping (narcolepsy).3.0` = col_character(),
`Current tobacco smoking.0.0` = col_character(),
`Current tobacco smoking.1.0` = col_character(),
`Current tobacco smoking.2.0` = col_character(),
`Current tobacco smoking.3.0` = col_character(),
`Past tobacco smoking.0.0` = col_character(),
`Past tobacco smoking.1.0` = col_character(),
`Past tobacco smoking.2.0` = col_character(),
`Past tobacco smoking.3.0` = col_character(),
`Smoking/smokers in household.0.0` = col_character(),
`Smoking/smokers in household.1.0` = col_character(),
`Smoking/smokers in household.2.0` = col_character(),
`Smoking/smokers in household.3.0` = col_character(),
`Exposure to tobacco smoke at home.0.0` = col_double(),
`Exposure to tobacco smoke at home.1.0` = col_double(),
`Exposure to tobacco smoke at home.2.0` = col_double(),
`Exposure to tobacco smoke at home.3.0` = col_double(),
`Exposure to tobacco smoke outside home.0.0` = col_double(),
`Exposure to tobacco smoke outside home.1.0` = col_double(),
`Exposure to tobacco smoke outside home.2.0` = col_double(),
`Exposure to tobacco smoke outside home.3.0` = col_double(),
`Oily fish intake.0.0` = col_character(),
`Oily fish intake.1.0` = col_character(),
`Oily fish intake.2.0` = col_character(),
`Oily fish intake.3.0` = col_character(),
`Non-oily fish intake.0.0` = col_character(),
`Non-oily fish intake.1.0` = col_character(),
`Non-oily fish intake.2.0` = col_character(),
`Non-oily fish intake.3.0` = col_character(),
`Alcohol intake frequency..0.0` = col_character(),
`Alcohol intake frequency..1.0` = col_character(),
`Alcohol intake frequency..2.0` = col_character(),
`Alcohol intake frequency..3.0` = col_character(),
`Country of birth (UK/elsewhere).0.0` = col_character(),
`Country of birth (UK/elsewhere).1.0` = col_character(),
`Country of birth (UK/elsewhere).2.0` = col_character(),
`Breastfed as a baby.0.0` = col_character(),
`Breastfed as a baby.1.0` = col_character(),
`Breastfed as a baby.2.0` = col_character(),
`Comparative body size at age 10.0.0` = col_character(),
`Comparative body size at age 10.1.0` = col_character(),
`Comparative body size at age 10.2.0` = col_character(),
`Comparative height size at age 10.0.0` = col_character(),
`Comparative height size at age 10.1.0` = col_character(),
`Comparative height size at age 10.2.0` = col_character(),
`Handedness (chirality/laterality).0.0` = col_character(),
`Handedness (chirality/laterality).1.0` = col_character(),
`Handedness (chirality/laterality).2.0` = col_character(),
`Childhood sunburn occasions.0.0` = col_double(),
`Childhood sunburn occasions.1.0` = col_double(),
`Childhood sunburn occasions.2.0` = col_double(),
`Part of a multiple birth.0.0` = col_character(),
`Part of a multiple birth.1.0` = col_character(),
`Part of a multiple birth.2.0` = col_character(),
`Maternal smoking around birth.0.0` = col_character(),
`Maternal smoking around birth.1.0` = col_character(),
`Maternal smoking around birth.2.0` = col_character(),
`Age first had sexual intercourse.0.0` = col_double(),
`Age first had sexual intercourse.1.0` = col_double(),
`Age first had sexual intercourse.2.0` = col_double(),
`Age first had sexual intercourse.3.0` = col_double(),
`Relative age of first facial hair.0.0` = col_character(),
`Relative age of first facial hair.1.0` = col_character(),
`Relative age of first facial hair.2.0` = col_character(),
`Relative age voice broke.0.0` = col_character(),
`Relative age voice broke.1.0` = col_character(),
`Relative age voice broke.2.0` = col_character(),
`Age when periods started (menarche).0.0` = col_double(),
`Age when periods started (menarche).1.0` = col_double(),
`Age when periods started (menarche).2.0` = col_double(),
`Age when periods started (menarche).3.0` = col_double(),
`Age started smoking in former smokers.0.0` = col_double(),
`Age started smoking in former smokers.1.0` = col_double(),
`Age started smoking in former smokers.2.0` = col_double(),
`Age started smoking in former smokers.3.0` = col_double(),
`Age stopped smoking.0.0` = col_double(),
`Age stopped smoking.1.0` = col_double(),
`Age stopped smoking.2.0` = col_double(),
`Age stopped smoking.3.0` = col_double(),
`Age started smoking in current smokers.0.0` = col_double(),
`Age started smoking in current smokers.1.0` = col_double(),
`Age started smoking in current smokers.2.0` = col_double(),
`Age started smoking in current smokers.3.0` = col_double(),
`Attendance/disability/mobility allowance.0.0` = col_character(),
`Attendance/disability/mobility allowance.0.1` = col_character(),
`Attendance/disability/mobility allowance.0.2` = col_character(),
`Vitamin and mineral supplements.0.0` = col_character(),
`Vitamin and mineral supplements.0.1` = col_character(),
`Vitamin and mineral supplements.0.2` = col_character(),
`Vitamin and mineral supplements.0.3` = col_character(),
`Vitamin and mineral supplements.0.4` = col_character(),
`Vitamin and mineral supplements.0.5` = col_character(),
`Vitamin and mineral supplements.0.6` = col_character(),
`Vitamin and mineral supplements.1.0` = col_character(),
`Vitamin and mineral supplements.1.1` = col_character(),
`Vitamin and mineral supplements.1.2` = col_character(),
`Vitamin and mineral supplements.1.3` = col_character(),
`Vitamin and mineral supplements.1.4` = col_character(),
`Vitamin and mineral supplements.1.5` = col_character(),
`Vitamin and mineral supplements.1.6` = col_character(),
`Vitamin and mineral supplements.2.0` = col_character(),
`Vitamin and mineral supplements.2.1` = col_character(),
`Vitamin and mineral supplements.2.2` = col_character(),
`Vitamin and mineral supplements.2.3` = col_character(),
`Vitamin and mineral supplements.2.4` = col_character(),
`Vitamin and mineral supplements.2.5` = col_character(),
`Vitamin and mineral supplements.2.6` = col_character(),
`Vitamin and mineral supplements.3.0` = col_character(),
`Vitamin and mineral supplements.3.1` = col_character(),
`Vitamin and mineral supplements.3.2` = col_character(),
`Vitamin and mineral supplements.3.3` = col_character(),
`Vitamin and mineral supplements.3.4` = col_character(),
`Vitamin and mineral supplements.3.5` = col_character(),
`Vitamin and mineral supplements.3.6` = col_logical(),
`Age stopped smoking cigarettes (current cigar/pipe or previous cigarette smoker).0.0` = col_double(),
`Age stopped smoking cigarettes (current cigar/pipe or previous cigarette smoker).1.0` = col_double(),
`Age stopped smoking cigarettes (current cigar/pipe or previous cigarette smoker).2.0` = col_double(),
`Non-cancer illness code, self-reported.0.0` = col_double(),
`Non-cancer illness code, self-reported.0.1` = col_double(),
`Non-cancer illness code, self-reported.0.2` = col_double(),
`Non-cancer illness code, self-reported.0.3` = col_double(),
`Non-cancer illness code, self-reported.0.4` = col_double(),
`Non-cancer illness code, self-reported.0.5` = col_double(),
`Non-cancer illness code, self-reported.0.6` = col_double(),
`Non-cancer illness code, self-reported.0.7` = col_double(),
`Non-cancer illness code, self-reported.0.8` = col_double(),
`Non-cancer illness code, self-reported.0.9` = col_double(),
`Non-cancer illness code, self-reported.0.10` = col_double(),
`Non-cancer illness code, self-reported.0.11` = col_double(),
`Non-cancer illness code, self-reported.0.12` = col_double(),
`Non-cancer illness code, self-reported.0.13` = col_double(),
`Non-cancer illness code, self-reported.0.14` = col_double(),
`Non-cancer illness code, self-reported.0.15` = col_double(),
`Non-cancer illness code, self-reported.0.16` = col_logical(),
`Non-cancer illness code, self-reported.0.17` = col_logical(),
`Non-cancer illness code, self-reported.0.18` = col_logical(),
`Non-cancer illness code, self-reported.0.19` = col_logical(),
`Non-cancer illness code, self-reported.0.20` = col_logical(),
`Non-cancer illness code, self-reported.0.21` = col_logical(),
`Non-cancer illness code, self-reported.0.22` = col_logical(),
`Non-cancer illness code, self-reported.0.23` = col_logical(),
`Non-cancer illness code, self-reported.0.24` = col_logical(),
`Non-cancer illness code, self-reported.0.25` = col_logical(),
`Non-cancer illness code, self-reported.0.26` = col_logical(),
`Non-cancer illness code, self-reported.0.27` = col_logical(),
`Non-cancer illness code, self-reported.0.28` = col_logical(),
`Non-cancer illness code, self-reported.0.29` = col_logical(),
`Non-cancer illness code, self-reported.0.30` = col_logical(),
`Non-cancer illness code, self-reported.0.31` = col_logical(),
`Non-cancer illness code, self-reported.0.32` = col_logical(),
`Non-cancer illness code, self-reported.0.33` = col_logical(),
`Non-cancer illness code, self-reported.1.0` = col_double(),
`Non-cancer illness code, self-reported.1.1` = col_double(),
`Non-cancer illness code, self-reported.1.2` = col_double(),
`Non-cancer illness code, self-reported.1.3` = col_double(),
`Non-cancer illness code, self-reported.1.4` = col_double(),
`Non-cancer illness code, self-reported.1.5` = col_double(),
`Non-cancer illness code, self-reported.1.6` = col_double(),
`Non-cancer illness code, self-reported.1.7` = col_double(),
`Non-cancer illness code, self-reported.1.8` = col_double(),
`Non-cancer illness code, self-reported.1.9` = col_double(),
`Non-cancer illness code, self-reported.1.10` = col_double(),
`Non-cancer illness code, self-reported.1.11` = col_double(),
`Non-cancer illness code, self-reported.1.12` = col_double(),
`Non-cancer illness code, self-reported.1.13` = col_double(),
`Non-cancer illness code, self-reported.1.14` = col_logical(),
`Non-cancer illness code, self-reported.1.15` = col_logical(),
`Non-cancer illness code, self-reported.1.16` = col_logical(),
`Non-cancer illness code, self-reported.1.17` = col_logical(),
`Non-cancer illness code, self-reported.1.18` = col_logical(),
`Non-cancer illness code, self-reported.1.19` = col_logical(),
`Non-cancer illness code, self-reported.1.20` = col_logical(),
`Non-cancer illness code, self-reported.1.21` = col_logical(),
`Non-cancer illness code, self-reported.1.22` = col_logical(),
`Non-cancer illness code, self-reported.1.23` = col_logical(),
`Non-cancer illness code, self-reported.1.24` = col_logical(),
`Non-cancer illness code, self-reported.1.25` = col_logical(),
`Non-cancer illness code, self-reported.1.26` = col_logical(),
`Non-cancer illness code, self-reported.1.27` = col_logical(),
`Non-cancer illness code, self-reported.1.28` = col_logical(),
`Non-cancer illness code, self-reported.1.29` = col_logical(),
`Non-cancer illness code, self-reported.1.30` = col_logical(),
`Non-cancer illness code, self-reported.1.31` = col_logical(),
`Non-cancer illness code, self-reported.1.32` = col_logical(),
`Non-cancer illness code, self-reported.1.33` = col_logical(),
`Non-cancer illness code, self-reported.2.0` = col_double(),
`Non-cancer illness code, self-reported.2.1` = col_double(),
`Non-cancer illness code, self-reported.2.2` = col_double(),
`Non-cancer illness code, self-reported.2.3` = col_double(),
`Non-cancer illness code, self-reported.2.4` = col_double(),
`Non-cancer illness code, self-reported.2.5` = col_double(),
`Non-cancer illness code, self-reported.2.6` = col_double(),
`Non-cancer illness code, self-reported.2.7` = col_double(),
`Non-cancer illness code, self-reported.2.8` = col_double(),
`Non-cancer illness code, self-reported.2.9` = col_double(),
`Non-cancer illness code, self-reported.2.10` = col_double(),
`Non-cancer illness code, self-reported.2.11` = col_double(),
`Non-cancer illness code, self-reported.2.12` = col_double(),
`Non-cancer illness code, self-reported.2.13` = col_double(),
`Non-cancer illness code, self-reported.2.14` = col_double(),
`Non-cancer illness code, self-reported.2.15` = col_double(),
`Non-cancer illness code, self-reported.2.16` = col_double(),
`Non-cancer illness code, self-reported.2.17` = col_double(),
`Non-cancer illness code, self-reported.2.18` = col_double(),
`Non-cancer illness code, self-reported.2.19` = col_double(),
`Non-cancer illness code, self-reported.2.20` = col_logical(),
`Non-cancer illness code, self-reported.2.21` = col_logical(),
`Non-cancer illness code, self-reported.2.22` = col_logical(),
`Non-cancer illness code, self-reported.2.23` = col_logical(),
`Non-cancer illness code, self-reported.2.24` = col_logical(),
`Non-cancer illness code, self-reported.2.25` = col_logical(),
`Non-cancer illness code, self-reported.2.26` = col_logical(),
`Non-cancer illness code, self-reported.2.27` = col_logical(),
`Non-cancer illness code, self-reported.2.28` = col_logical(),
`Non-cancer illness code, self-reported.2.29` = col_logical(),
`Non-cancer illness code, self-reported.2.30` = col_logical(),
`Non-cancer illness code, self-reported.2.31` = col_logical(),
`Non-cancer illness code, self-reported.2.32` = col_logical(),
`Non-cancer illness code, self-reported.2.33` = col_logical(),
`Non-cancer illness code, self-reported.3.0` = col_double(),
`Non-cancer illness code, self-reported.3.1` = col_double(),
`Non-cancer illness code, self-reported.3.2` = col_double(),
`Non-cancer illness code, self-reported.3.3` = col_double(),
`Non-cancer illness code, self-reported.3.4` = col_double(),
`Non-cancer illness code, self-reported.3.5` = col_double(),
`Non-cancer illness code, self-reported.3.6` = col_double(),
`Non-cancer illness code, self-reported.3.7` = col_double(),
`Non-cancer illness code, self-reported.3.8` = col_double(),
`Non-cancer illness code, self-reported.3.9` = col_logical(),
`Non-cancer illness code, self-reported.3.10` = col_logical(),
`Non-cancer illness code, self-reported.3.11` = col_logical(),
`Non-cancer illness code, self-reported.3.12` = col_logical(),
`Non-cancer illness code, self-reported.3.13` = col_logical(),
`Non-cancer illness code, self-reported.3.14` = col_logical(),
`Non-cancer illness code, self-reported.3.15` = col_logical(),
`Non-cancer illness code, self-reported.3.16` = col_logical(),
`Non-cancer illness code, self-reported.3.17` = col_logical(),
`Non-cancer illness code, self-reported.3.18` = col_logical(),
`Non-cancer illness code, self-reported.3.19` = col_logical(),
`Non-cancer illness code, self-reported.3.20` = col_logical(),
`Non-cancer illness code, self-reported.3.21` = col_logical(),
`Non-cancer illness code, self-reported.3.22` = col_logical(),
`Non-cancer illness code, self-reported.3.23` = col_logical(),
`Non-cancer illness code, self-reported.3.24` = col_logical(),
`Non-cancer illness code, self-reported.3.25` = col_logical(),
`Non-cancer illness code, self-reported.3.26` = col_logical(),
`Non-cancer illness code, self-reported.3.27` = col_logical(),
`Non-cancer illness code, self-reported.3.28` = col_logical(),
`Non-cancer illness code, self-reported.3.29` = col_logical(),
`Non-cancer illness code, self-reported.3.30` = col_logical(),
`Non-cancer illness code, self-reported.3.31` = col_logical(),
`Non-cancer illness code, self-reported.3.32` = col_logical(),
`Non-cancer illness code, self-reported.3.33` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.0` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.1` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.2` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.3` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.4` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.5` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.6` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.7` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.8` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.9` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.10` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.11` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.12` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.13` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.14` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.15` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.16` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.17` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.18` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.19` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.20` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.21` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.22` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.23` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.24` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.25` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.26` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.27` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.28` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.29` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.30` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.31` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.32` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.0.33` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.0` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.1` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.2` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.3` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.4` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.5` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.6` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.7` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.8` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.9` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.10` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.11` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.12` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.13` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.14` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.15` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.16` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.17` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.18` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.19` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.20` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.21` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.22` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.23` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.24` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.25` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.26` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.27` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.28` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.29` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.30` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.31` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.32` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.1.33` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.0` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.1` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.2` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.3` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.4` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.5` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.6` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.7` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.8` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.9` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.10` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.11` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.12` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.13` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.14` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.15` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.16` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.17` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.18` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.19` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.20` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.21` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.22` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.23` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.24` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.25` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.26` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.27` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.28` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.29` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.30` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.31` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.32` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.2.33` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.0` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.1` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.2` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.3` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.4` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.5` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.6` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.7` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.8` = col_double(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.9` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.10` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.11` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.12` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.13` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.14` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.15` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.16` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.17` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.18` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.19` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.20` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.21` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.22` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.23` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.24` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.25` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.26` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.27` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.28` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.29` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.30` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.31` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.32` = col_logical(),
`Interpolated Age of participant when non-cancer illness first diagnosed.3.33` = col_logical(),
`Birth weight.0.0` = col_double(),
`Birth weight.1.0` = col_double(),
`Birth weight.2.0` = col_double(),
`Illnesses of father.0.0` = col_character(),
`Illnesses of father.0.1` = col_character(),
`Illnesses of father.0.2` = col_character(),
`Illnesses of father.0.3` = col_character(),
`Illnesses of father.0.4` = col_character(),
`Illnesses of father.0.5` = col_character(),
`Illnesses of father.0.6` = col_character(),
`Illnesses of father.0.7` = col_logical(),
`Illnesses of father.0.8` = col_logical(),
`Illnesses of father.0.9` = col_logical(),
`Illnesses of father.1.0` = col_character(),
`Illnesses of father.1.1` = col_character(),
`Illnesses of father.1.2` = col_character(),
`Illnesses of father.1.3` = col_character(),
`Illnesses of father.1.4` = col_character(),
`Illnesses of father.1.5` = col_logical(),
`Illnesses of father.1.6` = col_logical(),
`Illnesses of father.1.7` = col_logical(),
`Illnesses of father.1.8` = col_logical(),
`Illnesses of father.1.9` = col_logical(),
`Illnesses of father.2.0` = col_character(),
`Illnesses of father.2.1` = col_character(),
`Illnesses of father.2.2` = col_character(),
`Illnesses of father.2.3` = col_character(),
`Illnesses of father.2.4` = col_character(),
`Illnesses of father.2.5` = col_logical(),
`Illnesses of father.2.6` = col_logical(),
`Illnesses of father.2.7` = col_logical(),
`Illnesses of father.2.8` = col_logical(),
`Illnesses of father.2.9` = col_logical(),
`Illnesses of father.3.0` = col_character(),
`Illnesses of father.3.1` = col_character(),
`Illnesses of father.3.2` = col_character(),
`Illnesses of father.3.3` = col_character(),
`Illnesses of father.3.4` = col_logical(),
`Illnesses of father.3.5` = col_logical(),
`Illnesses of father.3.6` = col_logical(),
`Illnesses of father.3.7` = col_logical(),
`Illnesses of father.3.8` = col_logical(),
`Illnesses of father.3.9` = col_logical(),
`Illnesses of mother.0.0` = col_character(),
`Illnesses of mother.0.1` = col_character(),
`Illnesses of mother.0.2` = col_character(),
`Illnesses of mother.0.3` = col_character(),
`Illnesses of mother.0.4` = col_character(),
`Illnesses of mother.0.5` = col_character(),
`Illnesses of mother.0.6` = col_logical(),
`Illnesses of mother.0.7` = col_logical(),
`Illnesses of mother.0.8` = col_logical(),
`Illnesses of mother.0.9` = col_logical(),
`Illnesses of mother.0.10` = col_logical(),
`Illnesses of mother.1.0` = col_character(),
`Illnesses of mother.1.1` = col_character(),
`Illnesses of mother.1.2` = col_character(),
`Illnesses of mother.1.3` = col_character(),
`Illnesses of mother.1.4` = col_character(),
`Illnesses of mother.1.5` = col_character(),
`Illnesses of mother.1.6` = col_logical(),
`Illnesses of mother.1.7` = col_logical(),
`Illnesses of mother.1.8` = col_logical(),
`Illnesses of mother.1.9` = col_logical(),
`Illnesses of mother.1.10` = col_logical(),
`Illnesses of mother.2.0` = col_character(),
`Illnesses of mother.2.1` = col_character(),
`Illnesses of mother.2.2` = col_character(),
`Illnesses of mother.2.3` = col_character(),
`Illnesses of mother.2.4` = col_character(),
`Illnesses of mother.2.5` = col_character(),
`Illnesses of mother.2.6` = col_logical(),
`Illnesses of mother.2.7` = col_logical(),
`Illnesses of mother.2.8` = col_logical(),
`Illnesses of mother.2.9` = col_logical(),
`Illnesses of mother.2.10` = col_logical(),
`Illnesses of mother.3.0` = col_character(),
`Illnesses of mother.3.1` = col_character(),
`Illnesses of mother.3.2` = col_character(),
`Illnesses of mother.3.3` = col_logical(),
`Illnesses of mother.3.4` = col_logical(),
`Illnesses of mother.3.5` = col_logical(),
`Illnesses of mother.3.6` = col_logical(),
`Illnesses of mother.3.7` = col_logical(),
`Illnesses of mother.3.8` = col_logical(),
`Illnesses of mother.3.9` = col_logical(),
`Illnesses of mother.3.10` = col_logical(),
`Illnesses of siblings.0.0` = col_character(),
`Illnesses of siblings.0.1` = col_character(),
`Illnesses of siblings.0.2` = col_character(),
`Illnesses of siblings.0.3` = col_character(),
`Illnesses of siblings.0.4` = col_character(),
`Illnesses of siblings.0.5` = col_character(),
`Illnesses of siblings.0.6` = col_character(),
`Illnesses of siblings.0.7` = col_logical(),
`Illnesses of siblings.0.8` = col_logical(),
`Illnesses of siblings.0.9` = col_logical(),
`Illnesses of siblings.0.10` = col_logical(),
`Illnesses of siblings.0.11` = col_logical(),
`Illnesses of siblings.1.0` = col_character(),
`Illnesses of siblings.1.1` = col_character(),
`Illnesses of siblings.1.2` = col_character(),
`Illnesses of siblings.1.3` = col_character(),
`Illnesses of siblings.1.4` = col_character(),
`Illnesses of siblings.1.5` = col_character(),
`Illnesses of siblings.1.6` = col_character(),
`Illnesses of siblings.1.7` = col_character(),
`Illnesses of siblings.1.8` = col_logical(),
`Illnesses of siblings.1.9` = col_logical(),
`Illnesses of siblings.1.10` = col_logical(),
`Illnesses of siblings.1.11` = col_logical(),
`Illnesses of siblings.2.0` = col_character(),
`Illnesses of siblings.2.1` = col_character(),
`Illnesses of siblings.2.2` = col_character(),
`Illnesses of siblings.2.3` = col_character(),
`Illnesses of siblings.2.4` = col_character(),
`Illnesses of siblings.2.5` = col_logical(),
`Illnesses of siblings.2.6` = col_logical(),
`Illnesses of siblings.2.7` = col_logical(),
`Illnesses of siblings.2.8` = col_logical(),
`Illnesses of siblings.2.9` = col_logical(),
`Illnesses of siblings.2.10` = col_logical(),
`Illnesses of siblings.2.11` = col_logical(),
`Illnesses of siblings.3.0` = col_character(),
`Illnesses of siblings.3.1` = col_character(),
`Illnesses of siblings.3.2` = col_character(),
`Illnesses of siblings.3.3` = col_character(),
`Illnesses of siblings.3.4` = col_character(),
`Illnesses of siblings.3.5` = col_logical(),
`Illnesses of siblings.3.6` = col_logical(),
`Illnesses of siblings.3.7` = col_logical(),
`Illnesses of siblings.3.8` = col_logical(),
`Illnesses of siblings.3.9` = col_logical(),
`Illnesses of siblings.3.10` = col_logical(),
`Illnesses of siblings.3.11` = col_logical(),
`Country of Birth (non-UK origin).0.0` = col_double(),
`Smoking status.0.0` = col_character(),
`Smoking status.1.0` = col_character(),
`Smoking status.2.0` = col_character(),
`Smoking status.3.0` = col_character(),
`Alcohol drinker status.0.0` = col_character(),
`Alcohol drinker status.1.0` = col_character(),
`Alcohol drinker status.2.0` = col_character(),
`Alcohol drinker status.3.0` = col_character(),
`Home area population density - urban or rural.0.0` = col_character(),
`Current employment status - corrected.0.0` = col_character(),
`Ever smoked.0.0` = col_character(),
`Ever smoked.1.0` = col_character(),
`Ever smoked.2.0` = col_character(),
`Ever smoked.3.0` = col_character(),
`Pack years of smoking.0.0` = col_double(),
`Pack years of smoking.1.0` = col_double(),
`Pack years of smoking.2.0` = col_double(),
`Pack years of smoking.3.0` = col_double(),
`Ethnic background.0.0` = col_character(),
`Ethnic background.1.0` = col_character(),
`Ethnic background.2.0` = col_character(),
`Body mass index (BMI).0.0` = col_double(),
`Body mass index (BMI).1.0` = col_double(),
`Body mass index (BMI).2.0` = col_double(),
`Body mass index (BMI).3.0` = col_double(),
`Genotype measurement batch.0.0` = col_double(),
`Genetic sex.0.0` = col_character(),
`CEL files.0.0` = col_character(),
Heterozygosity.0.0 = col_double(),
`Heterozygosity, PCA corrected.0.0` = col_double(),
Missingness.0.0 = col_double(),
`Genetic ethnic grouping.0.0` = col_character(),
`Genetic principal components.0.1` = col_double(),
`Genetic principal components.0.2` = col_double(),
`Genetic principal components.0.3` = col_double(),
`Genetic principal components.0.4` = col_double(),
`Genetic principal components.0.5` = col_double(),
`Genetic principal components.0.6` = col_double(),
`Genetic principal components.0.7` = col_double(),
`Genetic principal components.0.8` = col_double(),
`Genetic principal components.0.9` = col_double(),
`Genetic principal components.0.10` = col_double(),
`Genetic principal components.0.11` = col_double(),
`Falls in the last year.0.0`=col_character(),
`Fractured/broken bones in last 5 years.0.0`=col_character(),
`Heel bone mineral density (BMD) T-score, automated.0.0`=col_character(),
`Usual walking pace.0.0`=col_character(),
`Genetic principal components.0.12` = col_double(),
`Genetic principal components.0.13` = col_double(),
`Genetic principal components.0.14` = col_double(),
`Genetic principal components.0.15` = col_double(),
`Genetic principal components.0.16` = col_double(),
`Genetic principal components.0.17` = col_double(),
`Genetic principal components.0.18` = col_double(),
`Genetic principal components.0.19` = col_double(),
`Genetic principal components.0.20` = col_double(),
`Genetic principal components.0.21` = col_double(),
`Genetic principal components.0.22` = col_double(),
`Genetic principal components.0.23` = col_double(),
`Genetic principal components.0.24` = col_double(),
`Genetic principal components.0.25` = col_double(),
`Genetic principal components.0.26` = col_double(),
`Genetic principal components.0.27` = col_double(),
`Genetic principal components.0.28` = col_double(),
`Genetic principal components.0.29` = col_double(),
`Genetic principal components.0.30` = col_double(),
`Genetic principal components.0.31` = col_double(),
`Genetic principal components.0.32` = col_double(),
`Genetic principal components.0.33` = col_double(),
`Genetic principal components.0.34` = col_double(),
`Genetic principal components.0.35` = col_double(),
`Genetic principal components.0.36` = col_double(),
`Genetic principal components.0.37` = col_double(),
`Genetic principal components.0.38` = col_double(),
`Genetic principal components.0.39` = col_double(),
`Genetic principal components.0.40` = col_double(),
`Recommended genomic analysis exclusions.0.0` = col_character(),
`Genetic relatedness pairing.0.0` = col_double(),
`Genetic relatedness pairing.0.1` = col_double(),
`Genetic relatedness pairing.0.2` = col_double(),
`Genetic relatedness pairing.0.3` = col_logical(),
`Genetic relatedness pairing.0.4` = col_logical(),
`Genetic relatedness factor.0.0` = col_double(),
`Genetic relatedness factor.0.1` = col_double(),
`Genetic relatedness factor.0.2` = col_double(),
`Genetic relatedness factor.0.3` = col_logical(),
`Genetic relatedness factor.0.4` = col_logical(),
`Genetic relatedness IBS0.0.0` = col_double(),
`Genetic relatedness IBS0.0.1` = col_double(),
`Genetic relatedness IBS0.0.2` = col_double(),
`Genetic relatedness IBS0.0.3` = col_logical(),
`Genetic relatedness IBS0.0.4` = col_logical(),
`Had menopause.0.0`= col_character(),
`Genetic relatedness exclusions.0.0` = col_character(),
`Sex chromosome aneuploidy.0.0` = col_character(),
`Used in genetic principal components.0.0` = col_character(),
`Genetic kinship to other participants.0.0` = col_character(),
`Outliers for heterozygosity or missing rate.0.0` = col_character(),
`HLA imputation values.0.0` = col_character(),
`Age of stopping smoking.0.0` = col_double(),
`Workplace full of chemical or other fumes.0.0` = col_character(),
`Workplace full of chemical or other fumes.0.1` = col_character(),
`Workplace full of chemical or other fumes.0.2` = col_character(),
`Workplace full of chemical or other fumes.0.3` = col_character(),
`Workplace full of chemical or other fumes.0.4` = col_character(),
`Workplace full of chemical or other fumes.0.5` = col_character(),
`Workplace full of chemical or other fumes.0.6` = col_character(),
`Workplace full of chemical or other fumes.0.7` = col_character(),
`Workplace full of chemical or other fumes.0.8` = col_character(),
`Workplace full of chemical or other fumes.0.9` = col_character(),
`Workplace full of chemical or other fumes.0.10` = col_character(),
`Workplace full of chemical or other fumes.0.11` = col_character(),
`Workplace full of chemical or other fumes.0.12` = col_character(),
`Workplace full of chemical or other fumes.0.13` = col_character(),
`Workplace full of chemical or other fumes.0.14` = col_character(),
`Workplace full of chemical or other fumes.0.15` = col_character(),
`Workplace full of chemical or other fumes.0.16` = col_character(),
`Workplace full of chemical or other fumes.0.17` = col_character(),
`Workplace full of chemical or other fumes.0.18` = col_logical(),
`Workplace full of chemical or other fumes.0.19` = col_logical(),
`Workplace full of chemical or other fumes.0.20` = col_logical(),
`Workplace full of chemical or other fumes.0.21` = col_logical(),
`Workplace full of chemical or other fumes.0.22` = col_logical(),
`Workplace full of chemical or other fumes.0.23` = col_logical(),
`Workplace full of chemical or other fumes.0.24` = col_logical(),
`Workplace full of chemical or other fumes.0.25` = col_logical(),
`Workplace full of chemical or other fumes.0.26` = col_logical(),
`Workplace full of chemical or other fumes.0.27` = col_logical(),
`Workplace full of chemical or other fumes.0.28` = col_logical(),
`Workplace full of chemical or other fumes.0.29` = col_logical(),
`Workplace full of chemical or other fumes.0.30` = col_logical(),
`Workplace full of chemical or other fumes.0.31` = col_logical(),
`Workplace full of chemical or other fumes.0.32` = col_logical(),
`Workplace full of chemical or other fumes.0.33` = col_logical(),
`Workplace full of chemical or other fumes.0.34` = col_logical(),
`Workplace full of chemical or other fumes.0.35` = col_logical(),
`Workplace full of chemical or other fumes.0.36` = col_logical(),
`Workplace full of chemical or other fumes.0.37` = col_logical(),
`Workplace full of chemical or other fumes.0.38` = col_logical(),
`Workplace full of chemical or other fumes.0.39` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.0` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.1` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.2` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.3` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.4` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.5` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.6` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.7` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.8` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.9` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.10` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.11` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.12` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.13` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.14` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.15` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.16` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.17` = col_character(),
`Workplace had a lot of cigarette smoke from other people smoking.0.18` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.19` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.20` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.21` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.22` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.23` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.24` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.25` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.26` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.27` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.28` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.29` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.30` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.31` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.32` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.33` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.34` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.35` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.36` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.37` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.38` = col_logical(),
`Workplace had a lot of cigarette smoke from other people smoking.0.39` = col_logical(),
`Worked with paints, thinners or glues.0.0` = col_character(),
`Worked with paints, thinners or glues.0.1` = col_character(),
`Worked with paints, thinners or glues.0.2` = col_character(),
`Worked with paints, thinners or glues.0.3` = col_character(),
`Worked with paints, thinners or glues.0.4` = col_character(),
`Worked with paints, thinners or glues.0.5` = col_character(),
`Worked with paints, thinners or glues.0.6` = col_character(),
`Worked with paints, thinners or glues.0.7` = col_character(),
`Worked with paints, thinners or glues.0.8` = col_character(),
`Worked with paints, thinners or glues.0.9` = col_character(),
`Worked with paints, thinners or glues.0.10` = col_character(),
`Worked with paints, thinners or glues.0.11` = col_character(),
`Worked with paints, thinners or glues.0.12` = col_character(),
`Worked with paints, thinners or glues.0.13` = col_character(),
`Worked with paints, thinners or glues.0.14` = col_character(),
`Worked with paints, thinners or glues.0.15` = col_character(),
`Worked with paints, thinners or glues.0.16` = col_character(),
`Worked with paints, thinners or glues.0.17` = col_character(),
`Worked with paints, thinners or glues.0.18` = col_logical(),
`Worked with paints, thinners or glues.0.19` = col_logical(),
`Worked with paints, thinners or glues.0.20` = col_logical(),
`Worked with paints, thinners or glues.0.21` = col_logical(),
`Worked with paints, thinners or glues.0.22` = col_logical(),
`Worked with paints, thinners or glues.0.23` = col_logical(),
`Worked with paints, thinners or glues.0.24` = col_logical(),
`Worked with paints, thinners or glues.0.25` = col_logical(),
`Worked with paints, thinners or glues.0.26` = col_logical(),
`Worked with paints, thinners or glues.0.27` = col_logical(),
`Worked with paints, thinners or glues.0.28` = col_logical(),
`Worked with paints, thinners or glues.0.29` = col_logical(),
`Worked with paints, thinners or glues.0.30` = col_logical(),
`Worked with paints, thinners or glues.0.31` = col_logical(),
`Worked with paints, thinners or glues.0.32` = col_logical(),
`Worked with paints, thinners or glues.0.33` = col_logical(),
`Worked with paints, thinners or glues.0.34` = col_logical(),
`Worked with paints, thinners or glues.0.35` = col_logical(),
`Worked with paints, thinners or glues.0.36` = col_logical(),
`Worked with paints, thinners or glues.0.37` = col_logical(),
`Worked with paints, thinners or glues.0.38` = col_logical(),
`Worked with paints, thinners or glues.0.39` = col_logical(),
`Worked with pesticides.0.0` = col_character(),
`Worked with pesticides.0.1` = col_character(),
`Worked with pesticides.0.2` = col_character(),
`Worked with pesticides.0.3` = col_character(),
`Worked with pesticides.0.4` = col_character(),
`Worked with pesticides.0.5` = col_character(),
`Worked with pesticides.0.6` = col_character(),
`Worked with pesticides.0.7` = col_character(),
`Worked with pesticides.0.8` = col_character(),
`Worked with pesticides.0.9` = col_character(),
`Worked with pesticides.0.10` = col_character(),
`Worked with pesticides.0.11` = col_character(),
`Worked with pesticides.0.12` = col_character(),
`Worked with pesticides.0.13` = col_character(),
`Worked with pesticides.0.14` = col_character(),
`Worked with pesticides.0.15` = col_character(),
`Worked with pesticides.0.16` = col_character(),
`Worked with pesticides.0.17` = col_character(),
`Worked with pesticides.0.18` = col_logical(),
`Worked with pesticides.0.19` = col_logical(),
`Worked with pesticides.0.20` = col_logical(),
`Worked with pesticides.0.21` = col_logical(),
`Worked with pesticides.0.22` = col_logical(),
`Worked with pesticides.0.23` = col_logical(),
`Worked with pesticides.0.24` = col_logical(),
`Worked with pesticides.0.25` = col_logical(),
`Worked with pesticides.0.26` = col_logical(),
`Worked with pesticides.0.27` = col_logical(),
`Worked with pesticides.0.28` = col_logical(),
`Worked with pesticides.0.29` = col_logical(),
`Worked with pesticides.0.30` = col_logical(),
`Worked with pesticides.0.31` = col_logical(),
`Worked with pesticides.0.32` = col_logical(),
`Worked with pesticides.0.33` = col_logical(),
`Worked with pesticides.0.34` = col_logical(),
`Worked with pesticides.0.35` = col_logical(),
`Worked with pesticides.0.36` = col_logical(),
`Worked with pesticides.0.37` = col_logical(),
`Worked with pesticides.0.38` = col_logical(),
`Worked with pesticides.0.39` = col_logical(),
`Workplace had a lot of diesel exhaust.0.0` = col_character(),
`Workplace had a lot of diesel exhaust.0.1` = col_character(),
`Workplace had a lot of diesel exhaust.0.2` = col_character(),
`Workplace had a lot of diesel exhaust.0.3` = col_character(),
`Workplace had a lot of diesel exhaust.0.4` = col_character(),
`Workplace had a lot of diesel exhaust.0.5` = col_character(),
`Workplace had a lot of diesel exhaust.0.6` = col_character(),
`Workplace had a lot of diesel exhaust.0.7` = col_character(),
`Workplace had a lot of diesel exhaust.0.8` = col_character(),
`Workplace had a lot of diesel exhaust.0.9` = col_character(),
`Workplace had a lot of diesel exhaust.0.10` = col_character(),
`Workplace had a lot of diesel exhaust.0.11` = col_character(),
`Workplace had a lot of diesel exhaust.0.12` = col_character(),
`Workplace had a lot of diesel exhaust.0.13` = col_character(),
`Workplace had a lot of diesel exhaust.0.14` = col_character(),
`Workplace had a lot of diesel exhaust.0.15` = col_character(),
`Workplace had a lot of diesel exhaust.0.16` = col_character(),
`Workplace had a lot of diesel exhaust.0.17` = col_character(),
`Workplace had a lot of diesel exhaust.0.18` = col_logical(),
`Workplace had a lot of diesel exhaust.0.19` = col_logical(),
`Workplace had a lot of diesel exhaust.0.20` = col_logical(),
`Workplace had a lot of diesel exhaust.0.21` = col_logical(),
`Workplace had a lot of diesel exhaust.0.22` = col_logical(),
`Workplace had a lot of diesel exhaust.0.23` = col_logical(),
`Workplace had a lot of diesel exhaust.0.24` = col_logical(),
`Workplace had a lot of diesel exhaust.0.25` = col_logical(),
`Workplace had a lot of diesel exhaust.0.26` = col_logical(),
`Workplace had a lot of diesel exhaust.0.27` = col_logical(),
`Workplace had a lot of diesel exhaust.0.28` = col_logical(),
`Workplace had a lot of diesel exhaust.0.29` = col_logical(),
`Workplace had a lot of diesel exhaust.0.30` = col_logical(),
`Workplace had a lot of diesel exhaust.0.31` = col_logical(),
`Workplace had a lot of diesel exhaust.0.32` = col_logical(),
`Workplace had a lot of diesel exhaust.0.33` = col_logical(),
`Workplace had a lot of diesel exhaust.0.34` = col_logical(),
`Workplace had a lot of diesel exhaust.0.35` = col_logical(),
`Workplace had a lot of diesel exhaust.0.36` = col_logical(),
`Workplace had a lot of diesel exhaust.0.37` = col_logical(),
`Workplace had a lot of diesel exhaust.0.38` = col_logical(),
`Workplace had a lot of diesel exhaust.0.39` = col_logical(),
`VCA p18 antigen for Epstein-Barr Virus.0.0` = col_double(),
`VCA p18 antigen for Epstein-Barr Virus.1.0` = col_double(),
`EBNA-1 antigen for Epstein-Barr Virus.0.0` = col_double(),
`EBNA-1 antigen for Epstein-Barr Virus.1.0` = col_double(),
`ZEBRA antigen for Epstein-Barr Virus.0.0` = col_double(),
`ZEBRA antigen for Epstein-Barr Virus.1.0` = col_double(),
`EA-D antigen for Epstein-Barr Virus.0.0` = col_double(),
`EA-D antigen for Epstein-Barr Virus.1.0` = col_double(),
`Date of attending assessment centre.0.0` = col_date(format = ""),
`SHBG assay date.0.0` = col_date(format = ""),
`SHBG assay date.1.0` = col_date(format = ""),
`SHBG aliquot.0.0` = col_character(),
`SHBG aliquot.1.0` = col_character(),
`SHBG correction level.0.0` = col_character(),
`SHBG correction level.1.0` = col_character(),
`SHBG correction reason.0.0` = col_character(),
`SHBG correction reason.1.0` = col_character(),
`SHBG missing reason.0.0` = col_character(),
`SHBG missing reason.1.0` = col_character(),
`SHBG reportability.0.0` = col_character(),
`SHBG reportability.1.0` = col_character(),
`Testosterone assay date.0.0` = col_date(format = ""),
`Testosterone assay date.1.0` = col_date(format = ""),
`Testosterone aliquot.0.0` = col_character(),
`Testosterone aliquot.1.0` = col_character(),
`Testosterone correction level.0.0` = col_character(),
`Testosterone correction level.1.0` = col_character(),
`Testosterone correction reason.0.0` = col_character(),
`Testosterone correction reason.1.0` = col_character(),
`Testosterone missing reason.0.0` = col_character(),
`Testosterone missing reason.1.0` = col_character(),
`Testosterone reportability.0.0` = col_character(),
`Testosterone reportability.1.0` = col_character(),
`Vitamin D assay date.0.0` = col_date(format = ""),
`Vitamin D assay date.1.0` = col_date(format = ""),
`Vitamin D aliquot.0.0` = col_character(),
`Vitamin D aliquot.1.0` = col_character(),
`Vitamin D correction level.0.0` = col_character(),
`Vitamin D correction level.1.0` = col_character(),
`Vitamin D correction reason.0.0` = col_character(),
`Vitamin D correction reason.1.0` = col_character(),
`Vitamin D missing reason.0.0` = col_character(),
`Vitamin D missing reason.1.0` = col_character(),
`Vitamin D reportability.0.0` = col_character(),
`Vitamin D reportability.1.0` = col_character(),
`Underlying (primary) cause of death: ICD10.0.0` = col_character(),
`Underlying (primary) cause of death: ICD10.1.0` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.0` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.1` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.2` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.3` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.4` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.5` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.6` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.7` = col_character(),
`Contributory (secondary) causes of death: ICD10.0.8` = col_logical(),
`Contributory (secondary) causes of death: ICD10.0.9` = col_logical(),
`Contributory (secondary) causes of death: ICD10.0.10` = col_logical(),
`Contributory (secondary) causes of death: ICD10.0.11` = col_logical(),
`Contributory (secondary) causes of death: ICD10.0.12` = col_logical(),
`Contributory (secondary) causes of death: ICD10.0.13` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.0` = col_character(),
`Contributory (secondary) causes of death: ICD10.1.1` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.2` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.3` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.4` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.5` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.6` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.7` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.8` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.9` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.10` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.11` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.12` = col_logical(),
`Contributory (secondary) causes of death: ICD10.1.13` = col_logical(),
`Type of cancer: ICD10.0.0` = col_character(),
`Type of cancer: ICD10.1.0` = col_character(),
`Type of cancer: ICD10.2.0` = col_character(),
`Type of cancer: ICD10.3.0` = col_character(),
`Type of cancer: ICD10.4.0` = col_character(),
`Type of cancer: ICD10.5.0` = col_character(),
`Type of cancer: ICD10.6.0` = col_logical(),
`Type of cancer: ICD10.7.0` = col_logical(),
`Type of cancer: ICD10.8.0` = col_logical(),
`Type of cancer: ICD10.9.0` = col_logical(),
`Type of cancer: ICD10.10.0` = col_logical(),
`Type of cancer: ICD10.11.0` = col_logical(),
`Type of cancer: ICD10.12.0` = col_logical(),
`Type of cancer: ICD10.13.0` = col_logical(),
`Type of cancer: ICD10.14.0` = col_logical(),
`Type of cancer: ICD10.15.0` = col_logical(),
`Type of cancer: ICD10.16.0` = col_logical(),
`Type of cancer: ICD9.0.0` = col_double(),
`Type of cancer: ICD9.1.0` = col_double(),
`Type of cancer: ICD9.2.0` = col_double(),
`Type of cancer: ICD9.3.0` = col_double(),
`Type of cancer: ICD9.4.0` = col_double(),
`Type of cancer: ICD9.5.0` = col_double(),
`Type of cancer: ICD9.6.0` = col_logical(),
`Type of cancer: ICD9.7.0` = col_logical(),
`Type of cancer: ICD9.8.0` = col_logical(),
`Type of cancer: ICD9.9.0` = col_logical(),
`Type of cancer: ICD9.10.0` = col_logical(),
`Type of cancer: ICD9.11.0` = col_logical(),
`Type of cancer: ICD9.12.0` = col_logical(),
`Type of cancer: ICD9.13.0` = col_logical(),
`Type of cancer: ICD9.14.0` = col_logical(),
`Diagnoses - main ICD10.0.0` = col_character(),
`Diagnoses - main ICD10.0.1` = col_character(),
`Diagnoses - main ICD10.0.2` = col_character(),
`Diagnoses - main ICD10.0.3` = col_character(),
`Diagnoses - main ICD10.0.4` = col_character(),
`Diagnoses - main ICD10.0.5` = col_character(),
`Diagnoses - main ICD10.0.6` = col_character(),
`Diagnoses - main ICD10.0.7` = col_character(),
`Diagnoses - main ICD10.0.8` = col_character(),
`Diagnoses - main ICD10.0.9` = col_character(),
`Diagnoses - main ICD10.0.10` = col_character(),
`Diagnoses - main ICD10.0.11` = col_character(),
`Diagnoses - main ICD10.0.12` = col_character(),
`Diagnoses - main ICD10.0.13` = col_character(),
`Diagnoses - main ICD10.0.14` = col_character(),
`Diagnoses - main ICD10.0.15` = col_character(),
`Diagnoses - main ICD10.0.16` = col_character(),
`Diagnoses - main ICD10.0.17` = col_character(),
`Diagnoses - main ICD10.0.18` = col_character(),
`Diagnoses - main ICD10.0.19` = col_character(),
`Diagnoses - main ICD10.0.20` = col_character(),
`Diagnoses - main ICD10.0.21` = col_character(),
`Diagnoses - main ICD10.0.22` = col_character(),
`Diagnoses - main ICD10.0.23` = col_character(),
`Diagnoses - main ICD10.0.24` = col_character(),
`Diagnoses - main ICD10.0.25` = col_character(),
`Diagnoses - main ICD10.0.26` = col_character(),
`Diagnoses - main ICD10.0.27` = col_character(),
`Diagnoses - main ICD10.0.28` = col_character(),
`Diagnoses - main ICD10.0.29` = col_character(),
`Diagnoses - main ICD10.0.30` = col_character(),
`Diagnoses - main ICD10.0.31` = col_character(),
`Diagnoses - main ICD10.0.32` = col_character(),
`Diagnoses - main ICD10.0.33` = col_character(),
`Diagnoses - main ICD10.0.34` = col_character(),
`Diagnoses - main ICD10.0.35` = col_character(),
`Diagnoses - main ICD10.0.36` = col_character(),
`Diagnoses - main ICD10.0.37` = col_character(),
`Diagnoses - main ICD10.0.38` = col_character(),
`Diagnoses - main ICD10.0.39` = col_character(),
`Diagnoses - main ICD10.0.40` = col_character(),
`Diagnoses - main ICD10.0.41` = col_character(),
`Diagnoses - main ICD10.0.42` = col_character(),
`Diagnoses - main ICD10.0.43` = col_character(),
`Diagnoses - main ICD10.0.44` = col_character(),
`Diagnoses - main ICD10.0.45` = col_logical(),
`Diagnoses - main ICD10.0.46` = col_logical(),
`Diagnoses - main ICD10.0.47` = col_logical(),
`Diagnoses - main ICD10.0.48` = col_logical(),
`Diagnoses - main ICD10.0.49` = col_logical(),
`Diagnoses - main ICD10.0.50` = col_logical(),
`Diagnoses - main ICD10.0.51` = col_logical(),
`Diagnoses - main ICD10.0.52` = col_logical(),
`Diagnoses - main ICD10.0.53` = col_logical(),
`Diagnoses - main ICD10.0.54` = col_logical(),
`Diagnoses - main ICD10.0.55` = col_logical(),
`Diagnoses - main ICD10.0.56` = col_logical(),
`Diagnoses - main ICD10.0.57` = col_logical(),
`Diagnoses - main ICD10.0.58` = col_logical(),
`Diagnoses - main ICD10.0.59` = col_logical(),
`Diagnoses - main ICD10.0.60` = col_logical(),
`Diagnoses - main ICD10.0.61` = col_logical(),
`Diagnoses - main ICD10.0.62` = col_logical(),
`Diagnoses - main ICD10.0.63` = col_logical(),
`Diagnoses - main ICD10.0.64` = col_logical(),
`Diagnoses - main ICD10.0.65` = col_logical(),
`Diagnoses - main ICD9.0.0` = col_character(),
`Diagnoses - main ICD9.0.1` = col_character(),
`Diagnoses - main ICD9.0.2` = col_character(),
`Diagnoses - main ICD9.0.3` = col_character(),
`Diagnoses - main ICD9.0.4` = col_character(),
`Diagnoses - main ICD9.0.5` = col_character(),
`Diagnoses - main ICD9.0.6` = col_character(),
`Diagnoses - main ICD9.0.7` = col_double(),
`Diagnoses - main ICD9.0.8` = col_character(),
`Diagnoses - main ICD9.0.9` = col_character(),
`Diagnoses - main ICD9.0.10` = col_double(),
`Diagnoses - main ICD9.0.11` = col_logical(),
`Diagnoses - main ICD9.0.12` = col_logical(),
`Diagnoses - main ICD9.0.13` = col_logical(),
`Diagnoses - main ICD9.0.14` = col_logical(),
`Diagnoses - main ICD9.0.15` = col_logical(),
`Diagnoses - main ICD9.0.16` = col_logical(),
`Diagnoses - main ICD9.0.17` = col_logical(),
`Diagnoses - main ICD9.0.18` = col_logical(),
`Diagnoses - main ICD9.0.19` = col_logical(),
`Diagnoses - main ICD9.0.20` = col_logical(),
`Diagnoses - main ICD9.0.21` = col_logical(),
`Diagnoses - main ICD9.0.22` = col_logical(),
`Diagnoses - main ICD9.0.23` = col_logical(),
`Diagnoses - main ICD9.0.24` = col_logical(),
`Diagnoses - main ICD9.0.25` = col_logical(),
`Diagnoses - main ICD9.0.26` = col_logical(),
`Diagnoses - main ICD9.0.27` = col_logical(),
`Diagnoses - secondary ICD10.0.0` = col_character(),
`Diagnoses - secondary ICD10.0.1` = col_character(),
`Diagnoses - secondary ICD10.0.2` = col_character(),
`Diagnoses - secondary ICD10.0.3` = col_character(),
`Diagnoses - secondary ICD10.0.4` = col_character(),
`Diagnoses - secondary ICD10.0.5` = col_character(),
`Diagnoses - secondary ICD10.0.6` = col_character(),
`Diagnoses - secondary ICD10.0.7` = col_character(),
`Diagnoses - secondary ICD10.0.8` = col_character(),
`Diagnoses - secondary ICD10.0.9` = col_character(),
`Diagnoses - secondary ICD10.0.10` = col_character(),
`Diagnoses - secondary ICD10.0.11` = col_character(),
`Diagnoses - secondary ICD10.0.12` = col_character(),
`Diagnoses - secondary ICD10.0.13` = col_character(),
`Diagnoses - secondary ICD10.0.14` = col_character(),
`Diagnoses - secondary ICD10.0.15` = col_character(),
`Diagnoses - secondary ICD10.0.16` = col_character(),
`Diagnoses - secondary ICD10.0.17` = col_character(),
`Diagnoses - secondary ICD10.0.18` = col_character(),
`Diagnoses - secondary ICD10.0.19` = col_character(),
`Diagnoses - secondary ICD10.0.20` = col_character(),
`Diagnoses - secondary ICD10.0.21` = col_character(),
`Diagnoses - secondary ICD10.0.22` = col_character(),
`Diagnoses - secondary ICD10.0.23` = col_character(),
`Diagnoses - secondary ICD10.0.24` = col_character(),
`Diagnoses - secondary ICD10.0.25` = col_character(),
`Diagnoses - secondary ICD10.0.26` = col_character(),
`Diagnoses - secondary ICD10.0.27` = col_character(),
`Diagnoses - secondary ICD10.0.28` = col_character(),
`Diagnoses - secondary ICD10.0.29` = col_character(),
`Diagnoses - secondary ICD10.0.30` = col_character(),
`Diagnoses - secondary ICD10.0.31` = col_character(),
`Diagnoses - secondary ICD10.0.32` = col_character(),
`Diagnoses - secondary ICD10.0.33` = col_character(),
`Diagnoses - secondary ICD10.0.34` = col_character(),
`Diagnoses - secondary ICD10.0.35` = col_character(),
`Diagnoses - secondary ICD10.0.36` = col_character(),
`Diagnoses - secondary ICD10.0.37` = col_character(),
`Diagnoses - secondary ICD10.0.38` = col_character(),
`Diagnoses - secondary ICD10.0.39` = col_character(),
`Diagnoses - secondary ICD10.0.40` = col_character(),
`Diagnoses - secondary ICD10.0.41` = col_character(),
`Diagnoses - secondary ICD10.0.42` = col_character(),
`Diagnoses - secondary ICD10.0.43` = col_character(),
`Diagnoses - secondary ICD10.0.44` = col_character(),
`Diagnoses - secondary ICD10.0.45` = col_character(),
`Diagnoses - secondary ICD10.0.46` = col_character(),
`Diagnoses - secondary ICD10.0.47` = col_character(),
`Diagnoses - secondary ICD10.0.48` = col_character(),
`Diagnoses - secondary ICD10.0.49` = col_character(),
`Diagnoses - secondary ICD10.0.50` = col_character(),
`Diagnoses - secondary ICD10.0.51` = col_character(),
`Diagnoses - secondary ICD10.0.52` = col_character(),
`Diagnoses - secondary ICD10.0.53` = col_character(),
`Diagnoses - secondary ICD10.0.54` = col_character(),
`Diagnoses - secondary ICD10.0.55` = col_character(),
`Diagnoses - secondary ICD10.0.56` = col_character(),
`Diagnoses - secondary ICD10.0.57` = col_character(),
`Diagnoses - secondary ICD10.0.58` = col_character(),
`Diagnoses - secondary ICD10.0.59` = col_character(),
`Diagnoses - secondary ICD10.0.60` = col_character(),
`Diagnoses - secondary ICD10.0.61` = col_character(),
`Diagnoses - secondary ICD10.0.62` = col_character(),
`Diagnoses - secondary ICD10.0.63` = col_character(),
`Diagnoses - secondary ICD10.0.64` = col_character(),
`Diagnoses - secondary ICD10.0.65` = col_character(),
`Diagnoses - secondary ICD10.0.66` = col_character(),
`Diagnoses - secondary ICD10.0.67` = col_character(),
`Diagnoses - secondary ICD10.0.68` = col_character(),
`Diagnoses - secondary ICD10.0.69` = col_character(),
`Diagnoses - secondary ICD10.0.70` = col_character(),
`Diagnoses - secondary ICD10.0.71` = col_character(),
`Diagnoses - secondary ICD10.0.72` = col_character(),
`Diagnoses - secondary ICD10.0.73` = col_character(),
`Diagnoses - secondary ICD10.0.74` = col_character(),
`Diagnoses - secondary ICD10.0.75` = col_character(),
`Diagnoses - secondary ICD10.0.76` = col_character(),
`Diagnoses - secondary ICD10.0.77` = col_character(),
`Diagnoses - secondary ICD10.0.78` = col_character(),
`Diagnoses - secondary ICD10.0.79` = col_character(),
`Diagnoses - secondary ICD10.0.80` = col_character(),
`Diagnoses - secondary ICD10.0.81` = col_character(),
`Diagnoses - secondary ICD10.0.82` = col_character(),
`Diagnoses - secondary ICD10.0.83` = col_character(),
`Diagnoses - secondary ICD10.0.84` = col_character(),
`Diagnoses - secondary ICD10.0.85` = col_character(),
`Diagnoses - secondary ICD10.0.86` = col_character(),
`Diagnoses - secondary ICD10.0.87` = col_character(),
`Diagnoses - secondary ICD10.0.88` = col_character(),
`Diagnoses - secondary ICD10.0.89` = col_character(),
`Diagnoses - secondary ICD10.0.90` = col_character(),
`Diagnoses - secondary ICD10.0.91` = col_character(),
`Diagnoses - secondary ICD10.0.92` = col_character(),
`Diagnoses - secondary ICD10.0.93` = col_character(),
`Diagnoses - secondary ICD10.0.94` = col_character(),
`Diagnoses - secondary ICD10.0.95` = col_character(),
`Diagnoses - secondary ICD10.0.96` = col_character(),
`Diagnoses - secondary ICD10.0.97` = col_character(),
`Diagnoses - secondary ICD10.0.98` = col_character(),
`Diagnoses - secondary ICD10.0.99` = col_character(),
`Diagnoses - secondary ICD10.0.100` = col_character(),
`Diagnoses - secondary ICD10.0.101` = col_character(),
`Diagnoses - secondary ICD10.0.102` = col_character(),
`Diagnoses - secondary ICD10.0.103` = col_character(),
`Diagnoses - secondary ICD10.0.104` = col_logical(),
`Diagnoses - secondary ICD10.0.105` = col_logical(),
`Diagnoses - secondary ICD10.0.106` = col_logical(),
`Diagnoses - secondary ICD10.0.107` = col_logical(),
`Diagnoses - secondary ICD10.0.108` = col_logical(),
`Diagnoses - secondary ICD10.0.109` = col_logical(),
`Diagnoses - secondary ICD10.0.110` = col_logical(),
`Diagnoses - secondary ICD10.0.111` = col_logical(),
`Diagnoses - secondary ICD10.0.112` = col_logical(),
`Diagnoses - secondary ICD10.0.113` = col_logical(),
`Diagnoses - secondary ICD10.0.114` = col_logical(),
`Diagnoses - secondary ICD10.0.115` = col_logical(),
`Diagnoses - secondary ICD10.0.116` = col_logical(),
`Diagnoses - secondary ICD10.0.117` = col_logical(),
`Diagnoses - secondary ICD10.0.118` = col_logical(),
`Diagnoses - secondary ICD10.0.119` = col_logical(),
`Diagnoses - secondary ICD10.0.120` = col_logical(),
`Diagnoses - secondary ICD10.0.121` = col_logical(),
`Diagnoses - secondary ICD10.0.122` = col_logical(),
`Diagnoses - secondary ICD10.0.123` = col_logical(),
`Diagnoses - secondary ICD10.0.124` = col_logical(),
`Diagnoses - secondary ICD10.0.125` = col_logical(),
`Diagnoses - secondary ICD10.0.126` = col_logical(),
`Diagnoses - secondary ICD10.0.127` = col_logical(),
`Diagnoses - secondary ICD10.0.128` = col_logical(),
`Diagnoses - secondary ICD10.0.129` = col_logical(),
`Diagnoses - secondary ICD10.0.130` = col_logical(),
`Diagnoses - secondary ICD10.0.131` = col_logical(),
`Diagnoses - secondary ICD10.0.132` = col_logical(),
`Diagnoses - secondary ICD10.0.133` = col_logical(),
`Diagnoses - secondary ICD10.0.134` = col_logical(),
`Diagnoses - secondary ICD10.0.135` = col_logical(),
`Diagnoses - secondary ICD10.0.136` = col_logical(),
`Diagnoses - secondary ICD10.0.137` = col_logical(),
`Diagnoses - secondary ICD10.0.138` = col_logical(),
`Diagnoses - secondary ICD10.0.139` = col_logical(),
`Diagnoses - secondary ICD10.0.140` = col_logical(),
`Diagnoses - secondary ICD10.0.141` = col_logical(),
`Diagnoses - secondary ICD10.0.142` = col_logical(),
`Diagnoses - secondary ICD10.0.143` = col_logical(),
`Diagnoses - secondary ICD10.0.144` = col_logical(),
`Diagnoses - secondary ICD10.0.145` = col_logical(),
`Diagnoses - secondary ICD10.0.146` = col_logical(),
`Diagnoses - secondary ICD10.0.147` = col_logical(),
`Diagnoses - secondary ICD10.0.148` = col_logical(),
`Diagnoses - secondary ICD10.0.149` = col_logical(),
`Diagnoses - secondary ICD10.0.150` = col_logical(),
`Diagnoses - secondary ICD10.0.151` = col_logical(),
`Diagnoses - secondary ICD10.0.152` = col_logical(),
`Diagnoses - secondary ICD10.0.153` = col_logical(),
`Diagnoses - secondary ICD10.0.154` = col_logical(),
`Diagnoses - secondary ICD10.0.155` = col_logical(),
`Diagnoses - secondary ICD10.0.156` = col_logical(),
`Diagnoses - secondary ICD10.0.157` = col_logical(),
`Diagnoses - secondary ICD10.0.158` = col_logical(),
`Diagnoses - secondary ICD10.0.159` = col_logical(),
`Diagnoses - secondary ICD10.0.160` = col_logical(),
`Diagnoses - secondary ICD10.0.161` = col_logical(),
`Diagnoses - secondary ICD10.0.162` = col_logical(),
`Diagnoses - secondary ICD10.0.163` = col_logical(),
`Diagnoses - secondary ICD10.0.164` = col_logical(),
`Diagnoses - secondary ICD10.0.165` = col_logical(),
`Diagnoses - secondary ICD10.0.166` = col_logical(),
`Diagnoses - secondary ICD10.0.167` = col_logical(),
`Diagnoses - secondary ICD10.0.168` = col_logical(),
`Diagnoses - secondary ICD10.0.169` = col_logical(),
`Diagnoses - secondary ICD10.0.170` = col_logical(),
`Diagnoses - secondary ICD10.0.171` = col_logical(),
`Diagnoses - secondary ICD10.0.172` = col_logical(),
`Diagnoses - secondary ICD10.0.173` = col_logical(),
`Diagnoses - secondary ICD10.0.174` = col_logical(),
`Diagnoses - secondary ICD10.0.175` = col_logical(),
`Diagnoses - secondary ICD10.0.176` = col_logical(),
`Diagnoses - secondary ICD10.0.177` = col_logical(),
`Diagnoses - secondary ICD10.0.178` = col_logical(),
`Diagnoses - secondary ICD10.0.179` = col_logical(),
`Diagnoses - secondary ICD10.0.180` = col_logical(),
`Diagnoses - secondary ICD10.0.181` = col_logical(),
`Diagnoses - secondary ICD10.0.182` = col_logical(),
`Diagnoses - secondary ICD10.0.183` = col_logical(),
`Diagnoses - secondary ICD9.0.0` = col_character(),
`Diagnoses - secondary ICD9.0.1` = col_character(),
`Diagnoses - secondary ICD9.0.2` = col_character(),
`Diagnoses - secondary ICD9.0.3` = col_character(),
`Diagnoses - secondary ICD9.0.4` = col_character(),
`Diagnoses - secondary ICD9.0.5` = col_character(),
`Diagnoses - secondary ICD9.0.6` = col_character(),
`Diagnoses - secondary ICD9.0.7` = col_character(),
`Diagnoses - secondary ICD9.0.8` = col_character(),
`Diagnoses - secondary ICD9.0.9` = col_character(),
`Diagnoses - secondary ICD9.0.10` = col_character(),
`Diagnoses - secondary ICD9.0.11` = col_character(),
`Diagnoses - secondary ICD9.0.12` = col_logical(),
`Diagnoses - secondary ICD9.0.13` = col_logical(),
`Diagnoses - secondary ICD9.0.14` = col_logical(),
`Diagnoses - secondary ICD9.0.15` = col_logical(),
`Diagnoses - secondary ICD9.0.16` = col_logical(),
`Diagnoses - secondary ICD9.0.17` = col_logical(),
`Diagnoses - secondary ICD9.0.18` = col_logical(),
`Diagnoses - secondary ICD9.0.19` = col_logical(),
`Diagnoses - secondary ICD9.0.20` = col_logical(),
`Diagnoses - secondary ICD9.0.21` = col_logical(),
`Diagnoses - secondary ICD9.0.22` = col_logical(),
`Diagnoses - secondary ICD9.0.23` = col_logical(),
`Diagnoses - secondary ICD9.0.24` = col_logical(),
`Diagnoses - secondary ICD9.0.25` = col_logical(),
`Diagnoses - secondary ICD9.0.26` = col_logical(),
`Diagnoses - secondary ICD9.0.27` = col_logical(),
`Diagnoses - secondary ICD9.0.28` = col_logical(),
`Diagnoses - secondary ICD9.0.29` = col_logical(),
`Coffee consumed.0.0` = col_character(),
`Coffee consumed.1.0` = col_character(),
`Coffee consumed.2.0` = col_character(),
`Coffee consumed.3.0` = col_character(),
`Coffee consumed.4.0` = col_character(),
`Time spend outdoors in summer.0.0` = col_character(),
`Time spent outdoors in winter.0.0` = col_character(),
`Use of sun/uv protection.0.0` = col_character()))


print("selected cols")
ms_cases = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="G35")) %>% mutate('MS_status' = 1)
non_ms_cases = new_bd %>% filter(!EID %in% ms_cases$EID)
print("got ICD MS cases")
icd9_ms_cases1 = non_ms_cases %>% filter_at(vars(contains('ICD9')),any_vars(.=="3409")) %>% mutate('MS_status' = 1)
non_ms_cases = non_ms_cases %>% filter(!EID %in% icd9_ms_cases1$EID)
icd9_ms_cases2 = non_ms_cases %>% filter_at(vars(contains('ICD9')),any_vars(.=="340")) %>% mutate('MS_status' = 1)
non_ms_cases = non_ms_cases %>% filter(!EID %in% icd9_ms_cases2$EID) %>% mutate('MS_status' = 0)
print("got ICD MS cases")
self_ms = non_ms_cases %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1261")) %>% mutate('MS_status' = 1)
non_ms_cases = non_ms_cases %>% filter(!EID %in% self_ms$EID) %>% mutate('MS_status' = 0)
new_bd = bind_rows(ms_cases,non_ms_cases,icd9_ms_cases1,icd9_ms_cases2,self_ms)
new_bd$MS_status = factor(new_bd$MS_status)
print("converted MS status")

# iritis
iritis_cases = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="H200"|.=="H201"|.=="H202"|.=="H208"|.=="H209"|.=="H300"|.=="H301"|.=="H302"|.=="H308"|.=="H309"|.=="H221")) %>% mutate('iritis_status' = 1)
self_iritis = new_bd %>% filter(!EID %in% iritis_cases$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1530")) %>% mutate('iritis_status' = 1)
non_iritis = new_bd %>% filter(!EID %in% iritis_cases$EID) %>% filter(!EID %in% self_iritis$EID) %>% mutate('iritis_status' = 0)
new_bd = bind_rows(iritis_cases,self_iritis,non_iritis)

icd_ibd = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="K500"|.=="K501"|.=="K508"|.=="K509"|.=="K510"|.=="K511"|.=="K512"|.=="K513"|.=="K514"|.=="K515"|.=="K518"|.=="K519")) %>% mutate('IBD_status' = 1)
self_ibd = new_bd %>% filter(!EID %in% icd_ibd$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1461"|.=="1462"|.=="1463")) %>% mutate('IBD_status' = 1)
no_ibd = new_bd %>% filter(!EID %in% icd_ibd$EID) %>% filter(!EID %in% self_ibd$EID) %>% mutate('IBD_status' = 0)
new_bd = bind_rows(icd_ibd,self_ibd,no_ibd)

icd_crohns = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="K500"|.=="K501"|.=="K508"|.=="K509")) %>% mutate('crohns_status' = 1)
self_crohns = new_bd %>% filter(!EID %in% icd_crohns$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1462")) %>% mutate('crohns_status' = 1)
no_crohns = new_bd %>% filter(!EID %in% icd_crohns$EID) %>% filter(!EID %in% self_crohns$EID) %>% mutate('crohns_status' = 0)
new_bd = bind_rows(icd_crohns,self_crohns,no_crohns)

icd_ra = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="M0530"|.=="M0531"|.=="M0532"|.=="M0533"|.=="M0534"|.=="M0535"|.=="M0536"|.=="M0537"|.=="M0538"|.=="M0539"|.=="M0580"|.=="M0581"|.=="M0582"|.=="M0583"|.=="M0584"|.=="M0585"|.=="M0586"|.=="M0587"|.=="M0588"|.=="M0589"|.=="M0590"|.=="M0591"|.=="M0592"|.=="M0593"|.=="M0594"|.=="M0595"|.=="M0596"|.=="M0597"|.=="M0598"|.=="M0599"|.=="M0600"|.=="M0601"|.=="M0602"|.=="M0603"|.=="M0604"|.=="M0605"|.=="M0606"|.=="M0607"|.=="M0608"|.=="M0609"|.=="M0690"|.=="M0691"|.=="M0692"|.=="M0693"|.=="M0694"|.=="M0695"|.=="M0696"|.=="M0697"|.=="M0698"|.=="M0699")) %>% mutate('RA_status' = 1)
self_ra = new_bd %>% filter(!EID %in% icd_ra$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1464")) %>% mutate('RA_status' = 1)
no_ra = new_bd %>% filter(!EID %in% icd_ra$EID) %>% filter(!EID %in% self_ra$EID) %>% mutate('RA_status' = 0)
new_bd = bind_rows(icd_ra, self_ra,no_ra)

icd_pbc = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="K743")) %>% mutate('PBC_status' = 1)
self_pbc = new_bd %>% filter(!EID %in% icd_pbc$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1506")) %>% mutate('PBC_status' = 1)
no_pbc = new_bd %>% filter(!EID %in% self_pbc$EID)  %>% filter(!EID %in% icd_pbc$EID) %>% mutate('PBC_status' = 0)
new_bd = bind_rows(icd_pbc,self_pbc,no_pbc)

icd_sle = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="M321"|.=="M328"|.=="M329"|.=="M3290")) %>% mutate('SLE_status' = 1)
self_sle = new_bd %>% filter(!EID %in% icd_sle$EID) %>%filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1381")) %>% mutate('SLE_status' = 1)
no_sle = new_bd %>% filter(!EID %in% self_sle$EID) %>% filter(!EID %in% icd_sle$EID) %>% mutate('SLE_status' = 0)
new_bd = bind_rows(icd_sle,self_sle,no_sle)

icd_sjog = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="M350")) %>% mutate('SJOG_status' = 1)
self_sjog = new_bd %>% filter(!EID %in% icd_sjog$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1382")) %>% mutate('SJOG_status' = 1)
no_sjog = new_bd %>% filter(!EID %in% self_sjog$EID) %>% filter(!EID %in% icd_sjog$EID) %>% mutate('SJOG_status' = 0)
new_bd = bind_rows(icd_sjog,self_sjog,no_sjog)

icd_ank_spond = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="M45X0"|.=="M45X1"|.=="M45X2"|.=="M45X3"|.=="M45X4"|.=="M45X5"|.=="M45X6"|.=="M45X7"|.=="M45X8"|.=="M45X9")) %>% mutate('ank_spond_status' = 1)
self_ank_spond = new_bd %>% filter(!EID %in% icd_ank_spond$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1313")) %>% mutate('ank_spond_status' = 1)
no_ank_spond = new_bd %>% filter(!EID %in% self_ank_spond$EID) %>% filter(!EID %in% icd_ank_spond$EID) %>% mutate('ank_spond_status' = 0)
new_bd = bind_rows(icd_ank_spond,self_ank_spond,no_ank_spond)

icd_sarcoid = new_bd %>% filter_at(vars(contains('ICD10')),any_vars(.=="D860"|.=="D861"|.=="D862"|.=="D863"|.=="D868"|.=="D869")) %>% mutate('sarcoid_status' = 1)
self_sarcoid = new_bd %>% filter(!EID %in% icd_sarcoid$EID) %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1371")) %>% mutate('sarcoid_status' = 1)
no_sarcoid = new_bd %>% filter(!EID %in% self_sarcoid$EID) %>% filter(!EID %in% icd_sarcoid$EID) %>% mutate('sarcoid_status' = 0)
new_bd = bind_rows(icd_sarcoid,self_sarcoid,no_sarcoid)

im = new_bd %>% filter_at(vars(contains('Non-cancer illness code, self-reported')),any_vars(.=="1567")) %>% mutate('IM_status' = 1)
non_im = new_bd %>% filter(!EID %in% im$EID) %>% mutate('IM_status' = 0)
new_bd = bind_rows(im,non_im)


new_df = new_bd %>% filter(MS_status==1) %>% select(contains("on-cancer"),EID)
age_at_ms_diagnosis = c()
eids=c()
for (i in 1:nrow(new_df)){
row = new_df[i,]
c=colnames(row)
t=t(row)
t=data.frame(cbind(t,c))
colnames(t)=c("a","b")
ms=t %>% filter(a==1261)
if (nrow(ms)==0){
next
} else {
s=str_split(ms$b,pattern="reported.")[[1]][2]
f=paste0("Interpolated Age of participant when non-cancer illness first diagnosed.",s)
if(is.na(row[[f]])){
  next
} else {
age = row[[f]]
age_at_ms_diagnosis <<- c(age_at_ms_diagnosis,age)
t=t %>% filter(b=="EID")
eid=as.numeric(as.character(t$a))
eids <<- c(eids,eid)
}
}
}
new_df = data.frame(cbind(eids,age_at_ms_diagnosis))
colnames(new_df)=c("EID","age_at_ms_diagnosis")
print("converting EIDs")

new_df$EID = as.numeric(as.character(new_df$EID))
new_bd$EID = as.numeric(as.character(new_bd$EID))
print("converted EIDs")

new_bd=left_join(new_bd,new_df,by="EID")


#get hla allele dosages

a02_doses = c()
for (i in 1:nrow(new_bd)){
  a02 = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][4]
  a02_doses <<- c(a02_doses,a02)
}
a022_doses = c()
for (i in 1:nrow(new_bd)){
  a022 = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][5]
  a022_doses <<- c(a022_doses,a022)
}
a023_doses = c()
for (i in 1:nrow(new_bd)){
  a023 = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][6]
  a023_doses <<- c(a023_doses,a023)
}
a025_doses = c()
for (i in 1:nrow(new_bd)){
  a025 = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][7]
  a025_doses <<- c(a025_doses,a025)
}

a026_doses = c()
for (i in 1:nrow(new_bd)){
  a026 = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][8]
  a026_doses <<- c(a026_doses,a026)
}
a027_doses = c()
for (i in 1:nrow(new_bd)){
  a027 = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][9]
  a027_doses <<- c(a027_doses,a027)
}


drb15_doses = c()
for (i in 1:nrow(new_bd)){
  drb = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][282]
  drb15_doses <<- c(drb15_doses,drb)
}
drb152_doses = c()
for (i in 1:nrow(new_bd)){
  drb = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][283]
  drb152_doses <<- c(drb152_doses,drb)
}
drb153_doses = c()
for (i in 1:nrow(new_bd)){
  drb = strsplit(new_bd$`HLA imputation values.0.0`[i][1],split=",")[[1]][284]
  drb153_doses <<- c(drb153_doses,drb)
}
new_bd = cbind(new_bd,drb15_doses,a02_doses,a022_doses,a023_doses,a025_doses,a026_doses,a027_doses,drb152_doses,drb153_doses)

new_bd$drb15 = as.numeric(as.character(new_bd$drb15_doses))
new_bd$a02 = as.numeric(as.character(new_bd$a02_doses))

new_bd = bind_rows(new_bd %>% filter(drb15<0.7) %>% mutate(DRB_15 = "0"),
                          new_bd %>% filter(drb15>=0.7 & drb15<=1.4) %>% mutate(DRB_15 = "1"),
                          new_bd %>% filter(drb15>1.4) %>% mutate(DRB_15 = "2"))

new_bd = bind_rows(new_bd %>% filter(a02<0.7) %>% mutate(A_02 = "0"),
                          new_bd %>% filter(a02>=0.7 & a02<=1.4) %>% mutate(A_02 = "1"),
                          new_bd %>% filter(a02>1.4) %>% mutate(A_02 = "2"))


print("got hla alleles. now saving final df")

new_bd = new_bd %>%
select(EID,
Sex.0.0,
`Year of birth.0.0`,
`Age at recruitment.0.0`,
`Month of birth.0.0`,
`Place of birth in UK - north co-ordinate.0.0`,
`Age completed full time education.0.0`,
`Country of birth (UK/elsewhere).0.0`,
`Breastfed as a baby.0.0`,
`Comparative body size at age 10.0.0`,
`Maternal smoking around birth.0.0`,
`Age first had sexual intercourse.0.0`,
`Relative age of first facial hair.0.0`,
`Relative age voice broke.0.0`,
`Age when periods started (menarche).0.0`,
`Birth weight.0.0`,
`Smoking status.0.0`,
`Ethnic background.0.0`,
`HLA imputation values.0.0`,
`Townsend deprivation index at recruitment.0.0`,
contains("enetic"),
MS_status,
contains("oking"),
contains("affeine"),
A_02,
DRB_15,
IBD_status,
RA_status,
PBC_status,
SLE_status,
SJOG_status,
ank_spond_status,
sarcoid_status,
crohns_status,
drb15_doses,a02_doses,a022_doses,a023_doses,a025_doses,a026_doses,a027_doses,drb152_doses,drb153_doses,
contains("diet"),
contains("supplement"),
contains("intake"),
contains("outdoors"),
contains("protection"),
`Alcohol drinker status.0.0`,
`Had menopause.0.0`,
`Falls in the last year.0.0`,
`Fractured/broken bones in last 5 years.0.0`,
`Heel bone mineral density (BMD) T-score, automated.0.0`,
`Usual walking pace.0.0`,
`Myopia diagnosis.0.0`,
contains("edication"),
age_at_ms_diagnosis,
contains("oking"),
contains("affeine"),
contains("offee"),
contains("lcohol intake frequency"),
contains("ody mass index"),
contains("ge completed full time education"),
`Vitamin D reportability.0.0` ,
`Childhood sunburn occasions.0.0`,
`Attendance/disability/mobility allowance.0.0`,
iritis_status,
IM_status)


write_tsv(new_bd,path=args[2])

